### ISSUE TITLE
Removing lines on the dissertation signature page

### ISSUE THREAD

**Issue by DMSwan** [linguistics/utexas-latex#4]
Hello, it's me again! Apparently as of the current format guidelines, the dissertation signature page should not have lines on it. Editing line 130 to:

    \vskip2\baselineskip\par%

Got rid of the signature lines for me.

**Comment by chbrown** [comment]
Good to know! Is that based on the appearance of the current official templates, or feedback from the format checking staff?

**Comment by DMSwan** [comment]
The current guidelines (posted here: https://utexas.box.com/shared/static/ffag6al7b0eaaqcheml6dcot9u3z6zit.pdf) don't have lines on the signature page, and when I turned in my title pages as part of my request for defense, I was given the feedback from somebody in the graduate school that I should remove the lines.

Bob Penman didn't catch it, but he's a nice guy and has looked at a changing format for so many years that I'm not surprised he might have missed it.

**Comment by chbrown** [comment]
Cool. I'm convinced.

IIRC, spacing between signatures was an issue on mine, so I replaced the rule with a fill, so that vertical spacing remains pretty much the same as before, just no rules.

(P.S. congrats on submitting your thesis 😁)
